spring:
  application:
    name: backend
  main:
    banner-mode: off
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:campaigns
    username: ${DB_USER:user}
    password: ${DB_PASSWORD:user}

init:
  emeraldAccount:
    initBalance: ${ACCOUNT_INIT_BALANCE:10000000}